# Generated by Django 4.2.15 on 2024-09-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messages',
            field=models.TextField(default=''),
        ),
    ]
